[package]
name = "xtask"
description = "Development tasks for SOLAR: the manifest and the API template"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
solar-apis.workspace = true
solar-core.workspace = true

[lints]
workspace = true
